### ISSUE TITLE
Nachkaufen für Lötworkshop

### ISSUE THREAD

**Issue by marove2000** [Binary-Kitchen/SolderingTutorial#24]
SMD:
- <s>SMD-Taster</s>
- <s>ICs</s>
- <s>Kondensator</s>
- <s>LEDs</s>

**Comment by marove2000** [comment]
Nachschub für:

- Spitzzangen
- AA Batterien
- 5x Schutzbrillen
- 5x Lötabsaugungen
- Stromversorgung für die Lötabsaugungen
- Lötschwämme

**Comment by dk5ee** [comment]
Is this still open?
