### ISSUE TITLE
Fehler/Improve ATX Breakout Anleitung 

### ISSUE THREAD

**Issue by Hetti** [Binary-Kitchen/SolderingTutorial#48]
Folgende drei Issues habe ich in der Anleitung entdeckt, relevant sowohl für DE als auch EN Anleitung

- 1.2k Ohm Widerstand steht in der Anleitung nur mit Beschriftung/Farbcode "122" -> erweitern auf "1201 oder 122"
- Der Controller Chip TPS2513 ist in der Anleitung mit U2 beschriftet. Am Board gibt es kein U2 sondern U1 bei den USB Ports.
- Auch TSP2513: Es ist laut Anleitung unklar wie man den Chip jetzt anlöten soll, da auf dem Board auf beiden Seiten ein Strich ist, wobei bei einer Seite noch ein Punkt beim Strich ist.
![grafik](https://user-images.githubusercontent.com/3261408/132999624-fe12dce6-2f7a-4b4a-85e6-6ac3e52b0f97.png)
6. b) besagt ja: Eine vertikale Linie (sehr fein, schlecht zu sehen) ist auf dem Chip und auf dem Board aufgedruckt. Beide Linien markieren die Richtung und müssen übereinstimmen.

Anhand der obigen Konstellation ists nicht 100% klar wo ich das jetzt anlöten soll. Ich würde es mit dem Strich Links bei der Linie wo "U1" steht anlöten. Ist das die richtige?

**Comment by rralf** [comment]
Servus Hetti!

Antworten kann ich dir keine geben. Aber wenn sich das geklärt hast, magst dann gleich nen Patch dafür schreiben?

Viele Grüße!

**Comment by Hetti** [comment]
Servus Ralf!
Meinst du ein Patch fürs Readme hier? https://github.com/Binary-Kitchen/SolderingTutorial/blob/master/ATXBreakoutBoardSMD/README.md

Weil LaTeX Sources für die Anleitung selber hab ich hier im Repo nicht gefunden.

**Comment by rralf** [comment]
@tbnobody oder @marove2000 können da vielleicht welterhelfen.

**Comment by marove2000** [comment]
Hi Hetti,

danke für deine Verbesserungen! Ich stimme dir da überall zu.

Farbcode bzw. Beschriftung kann in der Readme einfach angepasst werden, das ist relativ trivial. Die Schritte können auch einfach durch Bearbeiten von CSV geändert werden. Für ATX hier: https://github.com/Binary-Kitchen/SolderingTutorial/tree/master/ATXBreakoutBoardSMD/manual/configuration

Danach ein make und die PDFs werden automatisch gebaut. Wenn du beim letzten Schritt Probleme hast, gib Bescheid dann kann auch einer von uns die neuen PDFs bauen.

**Comment by Hetti** [comment]
pull request ist raus mit den fixes
