### ISSUE TITLE
DiceDIP Fehler in Anleitung

### ISSUE THREAD

**Issue by marove2000** [Binary-Kitchen/SolderingTutorial#5]
Folgende Dinge müssen noch ergänzt werden:

1. Neue Bilder mit Sockel
2. IC in Sockel Stecken (ganz am Ende fehlt)
3. Schalter braucht ein wenig Gewalt um in die Löcher zu passen
4. Batteriehalter anklemmen (siehe Foto bzw. VCC = rot, GND = schwarz
5. Nochmal beim Kondensator besser eingehen, dass die Polung sehr wichtig ist!

**Comment by marove2000** [comment]
6. Dokumentieren, dass Würfel von alleine aus geht

**Comment by ventilator** [comment]
zu Punkt 3: oder ohne Durchstecken anlöten. Die Löcher sind schon arg klein
zu Punkt 5: vermutlich ist die Diode gemeint?
