### ISSUE TITLE
Checkliste für Fehlerquellen erstenn

### ISSUE THREAD

**Issue by marove2000** [Binary-Kitchen/SolderingTutorial#9]
Dazu eine Liste mit den Bausätzen und den dazu üblichen Fehlern. Beispiele:

Batteriehalter: Kabel nicht abisoliert
Würfel: Diode falsch herum
DIP Leds falsch herum
µController nicht richtig reingedrückt in Sockel
SMD LEDs nochmal festlöten

**Comment by ventilator** [comment]
![folie1](https://user-images.githubusercontent.com/4276067/27292483-dff08e0e-5513-11e7-848e-035073479665.PNG)
![folie2](https://user-images.githubusercontent.com/4276067/27292484-e015a3ce-5513-11e7-9325-25c6a3d23284.PNG)
[Fehlersuche DIP und SMD.pptx](https://github.com/Binary-Kitchen/SolderingTutorial/files/1085462/Fehlersuche.DIP.und.SMD.pptx)

Fehlercheckliste

**Comment by ventilator** [comment]
pushed to master.

**Comment by marove2000** [comment]
Moved to csv.
